spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 729186
    url: jdbc:mysql:///car?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
#    prefix: classpath:/templates
    prefix: classpath:/static
    suffix: .html
    cache: false
#  resources:
#    static-locations: classpath:/static/
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

#  mvc:
#    static-path-pattern: /css/**
server:
  port: 8082
